AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda for scraping game statistics to save in the baseball dynamo table

Parameters:
  MemorySize:
    Type: Number
    Default: 128
  LogLevel:
    Type: String
    Default: debug
  DynamoTableName:
    Type: String
    Default: baseball-table
  LogGroupRetentionDays:
    Type: Number
    Default: 60
  DynamoTableArn:
    Type: String
    Default: PIPELINE_OVERRIDE
  ApiGatewayId:
    Type: String
    Default: PIPELINE OVERRIDE

Resources:
  TeamWebScraperLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: CRON job web scraper for saving game statistics to the baseball dynamo table
      Runtime: python3.8
      CodeUri: ./../dist
      Timeout: 60
      Handler: ./
      FunctionName: !Sub ${AWS::StackName}-game-web-scraper
      MemorySize: !Ref MemorySize
      Events:
        Type: Schedule
        Properties:
          Name: Game Web Scraper Schedule
          Description: Schedule for triggering the game web scraper lambda (7AM UTC every day)
          Enabled: True
          Schedule: 'cron(0 7 * * ? *)'
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          DYNAMO_TABLE: !Ref DynamoTableName
          AWS_REGION_NAME: !Sub ${AWS::Region}
      AutoPublishAlias: live
      Tracing: Active
      DeploymentPreference:
        Type: AllAtOnce
      Tags:
        Product: Baseball
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - logs:PutLogEvents
              - logs:CreateLogStream
              - logs:CreateLogGroup
            Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:DeleteItem
            Resource: !Ref DynamoTableArn

  GameWebScraperLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PlayerWebScraperLambda
      Principal: apigateway.amazonaws.com

  GameWebScraperLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: !Ref LogGroupRetentionDays
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref PlayerWebScraperLambda]]

Outputs:
  GameWebScraperLambdaArn:
    Value: !GetAtt GameWebScraperLambda.Arn
    Description: Game stats web scraper Lambda Arn